In [1]:
!unzip /content/archive.zip

Archive:  /content/archive.zip
  inflating: tweets.csv

In [4]:
import pandas as pd

df = pd.read_csv("/content/tweets.csv", encoding='latin1')

In [5]:
df

,Target,ID,Date,flag,User,Text
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew
...,...,...,...,...,...,...
1048570,4,1960186342,Fri May 29 07:33:44 PDT 2009,NO_QUERY,Madelinedugganx,My GrandMa is making Dinenr with my Mum
1048571,4,1960186409,Fri May 29 07:33:43 PDT 2009,NO_QUERY,OffRoad_Dude,Mid-morning snack time... A bowl of cheese noo...
1048572,4,1960186429,Fri May 29 07:33:44 PDT 2009,NO_QUERY,Falchion,@ShaDeLa same here say it like from the Termi...
1048573,4,1960186445,Fri May 29 07:33:44 PDT 2009,NO_QUERY,jonasobsessedx,@DestinyHope92 im great thaanks wbuu?
1048574,4,1960186607,Fri May 29 07:33:45 PDT 2009,NO_QUERY,sugababez,cant wait til her date this weekend

In [8]:
print("=====================================================================")
print("\n")
print(df.shape)
print("=====================================================================")
print("\n")
print(df.columns)
print("=====================================================================")
print("\n")
print(df.head())
print("=====================================================================")
print("\n")
print(df.info())

=====================================================================


(1048575, 6)
=====================================================================


Index(['Target', 'ID', 'Date', 'flag', 'User', 'Text'], dtype='object')
=====================================================================


   Target          ID                          Date      flag           User  \
0       0  1467810672  Mon Apr 06 22:19:49 PDT 2009  NO_QUERY  scotthamilton
1       0  1467810917  Mon Apr 06 22:19:53 PDT 2009  NO_QUERY       mattycus
2       0  1467811184  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY        ElleCTF
3       0  1467811193  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY         Karoli
4       0  1467811372  Mon Apr 06 22:20:00 PDT 2009  NO_QUERY       joy_wolf

                                                Text
0  is upset that he can't update his Facebook by ...
1  @Kenichan I dived many times for the ball. Man...
2    my whole body feels itchy and like its on fire
3  @nationwideclass no, it's not behaving at all....
4                      @Kwesidei not the whole crew
=====================================================================


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 6 columns):
 #   Column  Non-Null Count    Dtype
---  ------  --------------    -----
 0   Target  1048575 non-null  int64
 1   ID      1048575 non-null  int64
 2   Date    1048575 non-null  object
 3   flag    1048575 non-null  object
 4   User    1048575 non-null  object
 5   Text    1048575 non-null  object
dtypes: int64(2), object(4)
memory usage: 48.0+ MB
None

In [10]:
df["Text"].head(10).to_list()

["is upset that he can't update his Facebook by texting it... and might cry as a result  School today also. Blah!",
 '@Kenichan I dived many times for the ball. Managed to save 50%  The rest go out of bounds',
 'my whole body feels itchy and like its on fire ',
 "@nationwideclass no, it's not behaving at all. i'm mad. why am i here? because I can't see you all over there. ",
 '@Kwesidei not the whole crew ',
 'Need a hug ',
 "@LOLTrish hey  long time no see! Yes.. Rains a bit ,only a bit  LOL , I'm fine thanks , how's you ?",
 "@Tatiana_K nope they didn't have it ",
 '@twittera que me muera ? ',
 "spring break in plain city... it's snowing "]

In [11]:
import pandas as pd
import re
import string

# NLTK
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download("stopwords")
nltk.download("wordnet")
nltk.download("omw-1.4")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

True

In [12]:
df["Text"].isnull().sum()

np.int64(0)

In [13]:
df["Text"].isnull().sum()

np.int64(0)

In [14]:
def remove_urls(text):
    return re.sub(r"https?://\S+|www\.\S+", "", text)

In [15]:
text = "Check this out https://example.com"
print(remove_urls(text))

Check this out

In [16]:
def remove_mentions(text):
    return re.sub(r"@\w+", "", text)

In [18]:
def handle_hashtags(text):
    return re.sub(r"#(\w+)", r"\1", text)

In [19]:
text = "I love this #AmazingMovie"
print(handle_hashtags(text))

I love this AmazingMovie

In [20]:
def handle_hashtags(text):
    return re.sub(r"#(\w+)", r"\1", text)

In [21]:
def lowercase(text):
    return text.lower()

In [22]:
def remove_punctuation(text):
    return text.translate(str.maketrans("", "", string.punctuation))

In [23]:
def remove_emojis(text):
    emoji_pattern = re.compile(
        "["
        "\U0001F600-\U0001F64F"
        "\U0001F300-\U0001F5FF"
        "\U0001F680-\U0001F6FF"
        "\U0001F1E0-\U0001F1FF"
        "\U00002702-\U000027B0"
        "\U000024C2-\U0001F251"
        "]+",
        flags=re.UNICODE
    )
    return emoji_pattern.sub(r"", text)

In [24]:
def normalize_repeated_chars(text):
    return re.sub(r"(.)\1{2,}", r"\1\1", text)

In [25]:
text = "I am soooo happyyyyyyy"
print(normalize_repeated_chars(text))

I am soo happyy

In [26]:
from nltk.tokenize import word_tokenize

nltk.download("punkt")
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [27]:
tokens = word_tokenize("I love you shoaib")
print(tokens)

['I', 'love', 'you', 'shoaib']

In [28]:
stop_words = set(stopwords.words("english"))

In [29]:
def remove_stopwords(tokens):
    return [word for word in tokens if word.lower() not in stop_words]

In [30]:
tokens = ["I", "love", "the", "NLP", "field"]

print(remove_stopwords(tokens))

['love', 'NLP', 'field']

In [31]:
lemmatizer = WordNetLemmatizer()

In [32]:
def lemmatize_tokens(tokens):
    return [
        lemmatizer.lemmatize(word)
        for word in tokens
    ]

In [35]:
def remove_html(text):
    return text # Placeholder for actual HTML removal logic

def preprocess_tweet(text):

    # 1. Remove URLs
    text = remove_urls(text)

    # 2. Remove mentions
    text = remove_mentions(text)

    # 3. Handle hashtags
    text = handle_hashtags(text)

    # 4. Remove HTML
    text = remove_html(text)

    # 5. Lowercase
    text = lowercase(text)

    # 6. Remove emojis
    text = remove_emojis(text)

    # 7. Normalize repeated characters
    text = normalize_repeated_chars(text)

    # 8. Remove punctuation
    text = remove_punctuation(text)

    # 9. Tokenization
    tokens = word_tokenize(text)

    # 10. Remove stopwords
    tokens = remove_stopwords(tokens)

    # 11. Lemmatization
    tokens = lemmatize_tokens(tokens)

    # 12. Convert tokens back to text
    return " ".join(tokens)

In [36]:
sample = df["Text"].iloc[1]

print("ORIGINAL:")
print(sample)

print("\nPROCESSED:")
print(preprocess_tweet(sample))

ORIGINAL:
@Kenichan I dived many times for the ball. Managed to save 50%  The rest go out of bounds

PROCESSED:
dived many time ball managed save 50 rest go bound

In [37]:
df["Processed_Text"] = df["Text"].apply(preprocess_tweet)

In [38]:
df[["Text", "Processed_Text"]].head(10)

,Text,Processed_Text
0,is upset that he can't update his Facebook by ...,upset cant update facebook texting might cry r...
1,@Kenichan I dived many times for the ball. Man...,dived many time ball managed save 50 rest go b...
2,my whole body feels itchy and like its on fire,whole body feel itchy like fire
3,"@nationwideclass no, it's not behaving at all....",behaving im mad cant see
4,@Kwesidei not the whole crew,whole crew
5,Need a hug,need hug
6,@LOLTrish hey long time no see! Yes.. Rains a...,hey long time see yes rain bit bit lol im fine...
7,@Tatiana_K nope they didn't have it,nope didnt
8,@twittera que me muera ?,que muera
9,spring break in plain city... it's snowing,spring break plain city snowing